package com.tarnvik.atom.model.converter;

import lombok.Getter;

public enum ISO639 {
  AAR("aar", "aa", "Afar"),
  ABK("abk", "ab", "Abkhazian"),
  ACE("ace", "", "Achinese"),
  ACH("ach", "", "Acoli"),
  ADA("ada", "", "Adangme"),
  ADY("ady", "", "Adyghe; Adygei"),
  AFA("afa", "", "Afro-Asiatic languages"),
  AFH("afh", "", "Afrihili"),
  AFR("afr", "af", "Afrikaans"),
  AIN("ain", "", "Ainu"),
  AKA("aka", "ak", "Akan"),
  AKK("akk", "", "Akkadian"),
  ALB_B("alb ", "sq", "Albanian"),
  SQI_T("sqi ", "", ""),
  ALE("ale", "", "Aleut"),
  ALG("alg", "", "Algonquian languages"),
  ALT("alt", "", "Southern Altai"),
  AMH("amh", "am", "Amharic"),
  ANG("ang", "", "English, Old (ca.450-1100)"),
  ANP("anp", "", "Angika"),
  APA("apa", "", "Apache languages"),
  ARA("ara", "ar", "Arabic"),
  ARC("arc", "", "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"),
  ARG("arg", "an", "Aragonese"),
  ARM_B("arm ", "hy", "Armenian"),
  HYE_T("hye ", "", ""),
  ARN("arn", "", "Mapudungun; Mapuche"),
  ARP("arp", "", "Arapaho"),
  ART("art", "", "Artificial languages"),
  ARW("arw", "", "Arawak"),
  ASM("asm", "as", "Assamese"),
  AST("ast", "", "Asturian; Bable; Leonese; Asturleonese"),
  ATH("ath", "", "Athapascan languages"),
  AUS("aus", "", "Australian languages"),
  AVA("ava", "av", "Avaric"),
  AVE("ave", "ae", "Avestan"),
  AWA("awa", "", "Awadhi"),
  AYM("aym", "ay", "Aymara"),
  AZE("aze", "az", "Azerbaijani"),
  BAD("bad", "", "Banda languages"),
  BAI("bai", "", "Bamileke languages"),
  BAK("bak", "ba", "Bashkir"),
  BAL("bal", "", "Baluchi"),
  BAM("bam", "bm", "Bambara"),
  BAN("ban", "", "Balinese"),
  BAQ_B("baq", "eu", "Basque"),
  EUS_T("eus", "", ""),
  BAS("bas", "", "Basa"),
  BAT("bat", "", "Baltic languages"),
  BEJ("bej", "", "Beja; Bedawiyet"),
  BEL("bel", "be", "Belarusian"),
  BEM("bem", "", "Bemba"),
  BEN("ben", "bn", "Bengali"),
  BER("ber", "", "Berber languages"),
  BHO("bho", "", "Bhojpuri"),
  BIH("bih", "bh", "Bihari languages"),
  BIK("bik", "", "Bikol"),
  BIN("bin", "", "Bini; Edo"),
  BIS("bis", "bi", "Bislama"),
  BLA("bla", "", "Siksika"),
  BNT("bnt", "", "Bantu languages"),
  TIB_B("tib ", "bo", "Tibetan"),
  BOD_T("bod ", "", ""),
  BOS("bos", "bs", "Bosnian"),
  BRA("bra", "", "Braj"),
  BRE("bre", "br", "Breton"),
  BTK("btk", "", "Batak languages"),
  BUA("bua", "", "Buriat"),
  BUG("bug", "", "Buginese"),
  BUL("bul", "bg", "Bulgarian"),
  BUR_B("bur ", "my", "Burmese"),
  MYA_T("mya ", "", ""),
  BYN("byn", "", "Blin; Bilin"),
  CAD("cad", "", "Caddo"),
  CAI("cai", "", "Central American Indian languages"),
  CAR("car", "", "Galibi Carib"),
  CAT("cat", "ca", "Catalan; Valencian"),
  CAU("cau", "", "Caucasian languages"),
  CEB("ceb", "", "Cebuano"),
  CEL("cel", "", "Celtic languages"),
  CZE_B("cze ", "cs", "Czech"),
  CES_T("ces ", "", ""),
  CHA("cha", "ch", "Chamorro"),
  CHB("chb", "", "Chibcha"),
  CHE("che", "ce", "Chechen"),
  CHG("chg", "", "Chagatai"),
  CHI_B("chi ", "zh", "Chinese"),
  ZHO_T("zho ", "", ""),
  CHK("chk", "", "Chuukese"),
  CHM("chm", "", "Mari"),
  CHN("chn", "", "Chinook jargon"),
  CHO("cho", "", "Choctaw"),
  CHP("chp", "", "Chipewyan; Dene Suline"),
  CHR("chr", "", "Cherokee"),
  CHU("chu", "cu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"),
  CHV("chv", "cv", "Chuvash"),
  CHY("chy", "", "Cheyenne"),
  CMC("cmc", "", "Chamic languages"),
  CNR("cnr", "", "Montenegrin"),
  COP("cop", "", "Coptic"),
  COR("cor", "kw", "Cornish"),
  COS("cos", "co", "Corsican"),
  CPE("cpe", "", "Creoles and pidgins, English based"),
  CPF("cpf", "", "Creoles and pidgins, French-based"),
  CPP("cpp", "", "Creoles and pidgins, Portuguese-based"),
  CRE("cre", "cr", "Cree"),
  CRH("crh", "", "Crimean Tatar; Crimean Turkish"),
  CRP("crp", "", "Creoles and pidgins"),
  CSB("csb", "", "Kashubian"),
  CUS("cus", "", "Cushitic languages"),
  WEL_B("wel ", "cy", "Welsh"),
  CYM_T("cym ", "", ""),
  DAK("dak", "", "Dakota"),
  DAN("dan", "da", "Danish"),
  DAR("dar", "", "Dargwa"),
  DAY("day", "", "Land Dayak languages"),
  DEL("del", "", "Delaware"),
  DEN("den", "", "Slave (Athapascan)"),
  GER_B("ger ", "de", "German"),
  DEU_T("deu ", "", ""),
  DGR("dgr", "", "Dogrib"),
  DIN("din", "", "Dinka"),
  DIV("div", "dv", "Divehi; Dhivehi; Maldivian"),
  DOI("doi", "", "Dogri"),
  DRA("dra", "", "Dravidian languages"),
  DSB("dsb", "", "Lower Sorbian"),
  DUA("dua", "", "Duala"),
  DUM("dum", "", "Dutch, Middle (ca.1050-1350)"),
  DUT_B("dut ", "nl", "Dutch; Flemish"),
  NLD_T("nld ", "", ""),
  DYU("dyu", "", "Dyula"),
  DZO("dzo", "dz", "Dzongkha"),
  EFI("efi", "", "Efik"),
  EGY("egy", "", "Egyptian (Ancient)"),
  EKA("eka", "", "Ekajuk"),
  GRE_B("gre", "el", "Greek, Modern (1453-)"),
  ELL_T("ell", "", ""),
  ELX("elx", "", "Elamite"),
  ENG("eng", "en", "English"),
  ENM("enm", "", "English, Middle (1100-1500)"),
  EPO("epo", "eo", "Esperanto"),
  EST("est", "et", "Estonian"),
  EWE("ewe", "ee", "Ewe"),
  EWO("ewo", "", "Ewondo"),
  FAN("fan", "", "Fang"),
  FAO("fao", "fo", "Faroese"),
  PER_B("per", "fa", "Persian"),
  FAS_T("fas", "", ""),
  FAT("fat", "", "Fanti"),
  FIJ("fij", "fj", "Fijian"),
  FIL("fil", "", "Filipino; Pilipino"),
  FIN("fin", "fi", "Finnish"),
  FIU("fiu", "", "Finno-Ugrian languages"),
  FON("fon", "", "Fon"),
  FRE_B("fre", "fr", "French"),
  FRA_T("fra", "", ""),
  FRM("frm", "", "French, Middle (ca.1400-1600)"),
  FRO("fro", "", "French, Old (842-ca.1400)"),
  FRR("frr", "", "Northern Frisian"),
  FRS("frs", "", "Eastern Frisian"),
  FRY("fry", "fy", "Western Frisian"),
  FUL("ful", "ff", "Fulah"),
  FUR("fur", "", "Friulian"),
  GAA("gaa", "", "Ga"),
  GAY("gay", "", "Gayo"),
  GBA("gba", "", "Gbaya"),
  GEM("gem", "", "Germanic languages"),
  GEO_B("geo", "ka", "Georgian"),
  KAT_T("kat", "", ""),
  GEZ("gez", "", "Geez"),
  GIL("gil", "", "Gilbertese"),
  GLA("gla", "gd", "Gaelic; Scottish Gaelic"),
  GLE("gle", "ga", "Irish"),
  GLG("glg", "gl", "Galician"),
  GLV("glv", "gv", "Manx"),
  GMH("gmh", "", "German, Middle High (ca.1050-1500)"),
  GOH("goh", "", "German, Old High (ca.750-1050)"),
  GON("gon", "", "Gondi"),
  GOR("gor", "", "Gorontalo"),
  GOT("got", "", "Gothic"),
  GRB("grb", "", "Grebo"),
  GRC("grc", "", "Greek, Ancient (to 1453)"),
  GRN("grn", "gn", "Guarani"),
  GSW("gsw", "", "Swiss German; Alemannic; Alsatian"),
  GUJ("guj", "gu", "Gujarati"),
  GWI("gwi", "", "Gwich'in"),
  HAI("hai", "", "Haida"),
  HAT("hat", "ht", "Haitian; Haitian Creole"),
  HAU("hau", "ha", "Hausa"),
  HAW("haw", "", "Hawaiian"),
  HEB("heb", "he", "Hebrew"),
  HER("her", "hz", "Herero"),
  HIL("hil", "", "Hiligaynon"),
  HIM("him", "", "Himachali languages; Western Pahari languages"),
  HIN("hin", "hi", "Hindi"),
  HIT("hit", "", "Hittite"),
  HMN("hmn", "", "Hmong; Mong"),
  HMO("hmo", "ho", "Hiri Motu"),
  HRV("hrv", "hr", "Croatian"),
  HSB("hsb", "", "Upper Sorbian"),
  HUN("hun", "hu", "Hungarian"),
  HUP("hup", "", "Hupa"),
  IBA("iba", "", "Iban"),
  IBO("ibo", "ig", "Igbo"),
  ICE_B("ice ", "is", "Icelandic"),
  ISL_T("isl ", "", ""),
  IDO("ido", "io", "Ido"),
  III("iii", "ii", "Sichuan Yi; Nuosu"),
  IJO("ijo", "", "Ijo languages"),
  IKU("iku", "iu", "Inuktitut"),
  ILE("ile", "ie", "Interlingue; Occidental"),
  ILO("ilo", "", "Iloko"),
  INA("ina", "ia", "Interlingua (International Auxiliary Language Association)"),
  INC("inc", "", "Indic languages"),
  IND("ind", "id", "Indonesian"),
  INE("ine", "", "Indo-European languages"),
  INH("inh", "", "Ingush"),
  IPK("ipk", "ik", "Inupiaq"),
  IRA("ira", "", "Iranian languages"),
  IRO("iro", "", "Iroquoian languages"),
  ITA("ita", "it", "Italian"),
  JAV("jav", "jv", "Javanese"),
  JBO("jbo", "", "Lojban"),
  JPN("jpn", "ja", "Japanese"),
  JPR("jpr", "", "Judeo-Persian"),
  JRB("jrb", "", "Judeo-Arabic"),
  KAA("kaa", "", "Kara-Kalpak"),
  KAB("kab", "", "Kabyle"),
  KAC("kac", "", "Kachin; Jingpho"),
  KAL("kal", "kl", "Kalaallisut; Greenlandic"),
  KAM("kam", "", "Kamba"),
  KAN("kan", "kn", "Kannada"),
  KAR("kar", "", "Karen languages"),
  KAS("kas", "ks", "Kashmiri"),
  KAU("kau", "kr", "Kanuri"),
  KAW("kaw", "", "Kawi"),
  KAZ("kaz", "kk", "Kazakh"),
  KBD("kbd", "", "Kabardian"),
  KHA("kha", "", "Khasi"),
  KHI("khi", "", "Khoisan languages"),
  KHM("khm", "km", "Central Khmer"),
  KHO("kho", "", "Khotanese; Sakan"),
  KIK("kik", "ki", "Kikuyu; Gikuyu"),
  KIN("kin", "rw", "Kinyarwanda"),
  KIR("kir", "ky", "Kirghiz; Kyrgyz"),
  KMB("kmb", "", "Kimbundu"),
  KOK("kok", "", "Konkani"),
  KOM("kom", "kv", "Komi"),
  KON("kon", "kg", "Kongo"),
  KOR("kor", "ko", "Korean"),
  KOS("kos", "", "Kosraean"),
  KPE("kpe", "", "Kpelle"),
  KRC("krc", "", "Karachay-Balkar"),
  KRL("krl", "", "Karelian"),
  KRO("kro", "", "Kru languages"),
  KRU("kru", "", "Kurukh"),
  KUA("kua", "kj", "Kuanyama; Kwanyama"),
  KUM("kum", "", "Kumyk"),
  KUR("kur", "ku", "Kurdish"),
  KUT("kut", "", "Kutenai"),
  LAD("lad", "", "Ladino"),
  LAH("lah", "", "Lahnda"),
  LAM("lam", "", "Lamba"),
  LAO("lao", "lo", "Lao"),
  LAT("lat", "la", "Latin"),
  LAV("lav", "lv", "Latvian"),
  LEZ("lez", "", "Lezghian"),
  LIM("lim", "li", "Limburgan; Limburger; Limburgish"),
  LIN("lin", "ln", "Lingala"),
  LIT("lit", "lt", "Lithuanian"),
  LOL("lol", "", "Mongo"),
  LOZ("loz", "", "Lozi"),
  LTZ("ltz", "lb", "Luxembourgish; Letzeburgesch"),
  LUA("lua", "", "Luba-Lulua"),
  LUB("lub", "lu", "Luba-Katanga"),
  LUG("lug", "lg", "Ganda"),
  LUI("lui", "", "Luiseno"),
  LUN("lun", "", "Lunda"),
  LUO("luo", "", "Luo (Kenya and Tanzania)"),
  LUS("lus", "", "Lushai"),
  MAC_B("mac", "mk", "Macedonian"),
  MKD_T("mkd", "", ""),
  MAD("mad", "", "Madurese"),
  MAG("mag", "", "Magahi"),
  MAH("mah", "mh", "Marshallese"),
  MAI("mai", "", "Maithili"),
  MAK("mak", "", "Makasar"),
  MAL("mal", "ml", "Malayalam"),
  MAN("man", "", "Mandingo"),
  MAO_B("mao ", "mi", "Maori"),
  MRI_T("mri ", "", ""),
  MAP("map", "", "Austronesian languages"),
  MAR("mar", "mr", "Marathi"),
  MAS("mas", "", "Masai"),
  MAY_B("may ", "ms", "Malay"),
  MSA_T("msa ", "", ""),
  MDF("mdf", "", "Moksha"),
  MDR("mdr", "", "Mandar"),
  MEN("men", "", "Mende"),
  MGA("mga", "", "Irish, Middle (900-1200)"),
  MIC("mic", "", "Mi'kmaq; Micmac"),
  MIN("min", "", "Minangkabau"),
  MIS("mis", "", "Uncoded languages"),
  MKH("mkh", "", "Mon-Khmer languages"),
  MLG("mlg", "mg", "Malagasy"),
  MLT("mlt", "mt", "Maltese"),
  MNC("mnc", "", "Manchu"),
  MNI("mni", "", "Manipuri"),
  MNO("mno", "", "Manobo languages"),
  MOH("moh", "", "Mohawk"),
  MON("mon", "mn", "Mongolian"),
  MOS("mos", "", "Mossi"),
  MUL("mul", "", "Multiple languages"),
  MUN("mun", "", "Munda languages"),
  MUS("mus", "", "Creek"),
  MWL("mwl", "", "Mirandese"),
  MWR("mwr", "", "Marwari"),
  MYN("myn", "", "Mayan languages"),
  MYV("myv", "", "Erzya"),
  NAH("nah", "", "Nahuatl languages"),
  NAI("nai", "", "North American Indian languages"),
  NAP("nap", "", "Neapolitan"),
  NAU("nau", "na", "Nauru"),
  NAV("nav", "nv", "Navajo; Navaho"),
  NBL("nbl", "nr", "Ndebele, South; South Ndebele"),
  NDE("nde", "nd", "Ndebele, North; North Ndebele"),
  NDO("ndo", "ng", "Ndonga"),
  NDS("nds", "", "Low German; Low Saxon; German, Low; Saxon, Low"),
  NEP("nep", "ne", "Nepali"),
  NEW_("new", "", "Nepal Bhasa; Newari"),
  NIA("nia", "", "Nias"),
  NIC("nic", "", "Niger-Kordofanian languages"),
  NIU("niu", "", "Niuean"),
  NNO("nno", "nn", "Norwegian Nynorsk; Nynorsk, Norwegian"),
  NOB("nob", "nb", "Bokmål, Norwegian; Norwegian Bokmål"),
  NOG("nog", "", "Nogai"),
  NON("non", "", "Norse, Old"),
  NOR("nor", "no", "Norwegian"),
  NQO("nqo", "", "N'Ko"),
  NSO("nso", "", "Pedi; Sepedi; Northern Sotho"),
  NUB("nub", "", "Nubian languages"),
  NWC("nwc", "", "Classical Newari; Old Newari; Classical Nepal Bhasa"),
  NYA("nya", "ny", "Chichewa; Chewa; Nyanja"),
  NYM("nym", "", "Nyamwezi"),
  NYN("nyn", "", "Nyankole"),
  NYO("nyo", "", "Nyoro"),
  NZI("nzi", "", "Nzima"),
  OCI("oci", "oc", "Occitan (post 1500)"),
  OJI("oji", "oj", "Ojibwa"),
  ORI("ori", "or", "Oriya"),
  ORM("orm", "om", "Oromo"),
  OSA("osa", "", "Osage"),
  OSS("oss", "os", "Ossetian; Ossetic"),
  OTA("ota", "", "Turkish, Ottoman (1500-1928)"),
  OTO("oto", "", "Otomian languages"),
  PAA("paa", "", "Papuan languages"),
  PAG("pag", "", "Pangasinan"),
  PAL("pal", "", "Pahlavi"),
  PAM("pam", "", "Pampanga; Kapampangan"),
  PAN("pan", "pa", "Panjabi; Punjabi"),
  PAP("pap", "", "Papiamento"),
  PAU("pau", "", "Palauan"),
  PEO("peo", "", "Persian, Old (ca.600-400 B.C.)"),
  PHI("phi", "", "Philippine languages"),
  PHN("phn", "", "Phoenician"),
  PLI("pli", "pi", "Pali"),
  POL("pol", "pl", "Polish"),
  PON("pon", "", "Pohnpeian"),
  POR("por", "pt", "Portuguese"),
  PRA("pra", "", "Prakrit languages"),
  PRO("pro", "", "Provençal, Old (to 1500);Occitan, Old (to 1500)"),
  PUS("pus", "ps", "Pushto; Pashto"),
  QAA_QTZ("qaa-qtz", "", "Reserved for local use"),
  QUE("que", "qu", "Quechua"),
  RAJ("raj", "", "Rajasthani"),
  RAP("rap", "", "Rapanui"),
  RAR("rar", "", "Rarotongan; Cook Islands Maori"),
  ROA("roa", "", "Romance languages"),
  ROH("roh", "rm", "Romansh"),
  ROM("rom", "", "Romany"),
  RUM_B("rum", "ro", "Romanian; Moldavian; Moldovan"),
  RON_T("ron", "", ""),
  RUN("run", "rn", "Rundi"),
  RUP("rup", "", "Aromanian; Arumanian; Macedo-Romanian"),
  RUS("rus", "ru", "Russian"),
  SAD("sad", "", "Sandawe"),
  SAG("sag", "sg", "Sango"),
  SAH("sah", "", "Yakut"),
  SAI("sai", "", "South American Indian languages"),
  SAL("sal", "", "Salishan languages"),
  SAM("sam", "", "Samaritan Aramaic"),
  SAN("san", "sa", "Sanskrit"),
  SAS("sas", "", "Sasak"),
  SAT("sat", "", "Santali"),
  SCN("scn", "", "Sicilian"),
  SCO("sco", "", "Scots"),
  SEL("sel", "", "Selkup"),
  SEM("sem", "", "Semitic languages"),
  SGA("sga", "", "Irish, Old (to 900)"),
  SGN("sgn", "", "Sign Languages"),
  SHN("shn", "", "Shan"),
  SID("sid", "", "Sidamo"),
  SIN("sin", "si", "Sinhala; Sinhalese"),
  SIO("sio", "", "Siouan languages"),
  SIT("sit", "", "Sino-Tibetan languages"),
  SLA("sla", "", "Slavic languages"),
  SLO_B("slo ", "sk", "Slovak"),
  SLK_T("slk ", "", ""),
  SLV("slv", "sl", "Slovenian"),
  SMA("sma", "", "Southern Sami"),
  SME("sme", "se", "Northern Sami"),
  SMI("smi", "", "Sami languages"),
  SMJ("smj", "", "Lule Sami"),
  SMN("smn", "", "Inari Sami"),
  SMO("smo", "sm", "Samoan"),
  SMS("sms", "", "Skolt Sami"),
  SNA("sna", "sn", "Shona"),
  SND("snd", "sd", "Sindhi"),
  SNK("snk", "", "Soninke"),
  SOG("sog", "", "Sogdian"),
  SOM("som", "so", "Somali"),
  SON("son", "", "Songhai languages"),
  SOT("sot", "st", "Sotho, Southern"),
  SPA("spa", "es", "Spanish; Castilian"),
  SRD("srd", "sc", "Sardinian"),
  SRN("srn", "", "Sranan Tongo"),
  SRP("srp", "sr", "Serbian"),
  SRR("srr", "", "Serer"),
  SSA("ssa", "", "Nilo-Saharan languages"),
  SSW("ssw", "ss", "Swati"),
  SUK("suk", "", "Sukuma"),
  SUN("sun", "su", "Sundanese"),
  SUS("sus", "", "Susu"),
  SUX("sux", "", "Sumerian"),
  SWA("swa", "sw", "Swahili"),
  SWE("swe", "sv", "Swedish"),
  SYC("syc", "", "Classical Syriac"),
  SYR("syr", "", "Syriac"),
  TAH("tah", "ty", "Tahitian"),
  TAI("tai", "", "Tai languages"),
  TAM("tam", "ta", "Tamil"),
  TAT("tat", "tt", "Tatar"),
  TEL("tel", "te", "Telugu"),
  TEM("tem", "", "Timne"),
  TER("ter", "", "Tereno"),
  TET("tet", "", "Tetum"),
  TGK("tgk", "tg", "Tajik"),
  TGL("tgl", "tl", "Tagalog"),
  THA("tha", "th", "Thai"),
  TIG("tig", "", "Tigre"),
  TIR("tir", "ti", "Tigrinya"),
  TIV("tiv", "", "Tiv"),
  TKL("tkl", "", "Tokelau"),
  TLH("tlh", "", "Klingon; tlhIngan-Hol"),
  TLI("tli", "", "Tlingit"),
  TMH("tmh", "", "Tamashek"),
  TOG("tog", "", "Tonga (Nyasa)"),
  TON("ton", "to", "Tonga (Tonga Islands)"),
  TPI("tpi", "", "Tok Pisin"),
  TSI("tsi", "", "Tsimshian"),
  TSN("tsn", "tn", "Tswana"),
  TSO("tso", "ts", "Tsonga"),
  TUK("tuk", "tk", "Turkmen"),
  TUM("tum", "", "Tumbuka"),
  TUP("tup", "", "Tupi languages"),
  TUR("tur", "tr", "Turkish"),
  TUT("tut", "", "Altaic languages"),
  TVL("tvl", "", "Tuvalu"),
  TWI("twi", "tw", "Twi"),
  TYV("tyv", "", "Tuvinian"),
  UDM("udm", "", "Udmurt"),
  UGA("uga", "", "Ugaritic"),
  UIG("uig", "ug", "Uighur; Uyghur"),
  UKR("ukr", "uk", "Ukrainian"),
  UMB("umb", "", "Umbundu"),
  UND("und", "", "Undetermined"),
  URD("urd", "ur", "Urdu"),
  UZB("uzb", "uz", "Uzbek"),
  VAI("vai", "", "Vai"),
  VEN("ven", "ve", "Venda"),
  VIE("vie", "vi", "Vietnamese"),
  VOL("vol", "vo", "Volapük"),
  VOT("vot", "", "Votic"),
  WAK("wak", "", "Wakashan languages"),
  WAL("wal", "", "Wolaitta; Wolaytta"),
  WAR("war", "", "Waray"),
  WAS("was", "", "Washo"),
  WEN("wen", "", "Sorbian languages"),
  WLN("wln", "wa", "Walloon"),
  WOL("wol", "wo", "Wolof"),
  XAL("xal", "", "Kalmyk; Oirat"),
  XHO("xho", "xh", "Xhosa"),
  YAO("yao", "", "Yao"),
  YAP("yap", "", "Yapese"),
  YID("yid", "yi", "Yiddish"),
  YOR("yor", "yo", "Yoruba"),
  YPK("ypk", "", "Yupik languages"),
  ZAP("zap", "", "Zapotec"),
  ZBL("zbl", "", "Blissymbols; Blissymbolics; Bliss"),
  ZEN("zen", "", "Zenaga"),
  ZGH("zgh", "", "Standard Moroccan Tamazight"),
  ZHA("zha", "za", "Zhuang; Chuang"),
  ZND("znd", "", "Zande languages"),
  ZUL("zul", "zu", "Zulu"),
  ZUN("zun", "", "Zuni"),
  ZXX("zxx", "", "No linguistic content; Not applicable"),
  ZZA("zza", "", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"),
  UNKNWON("", "", "Unknown");

  @Getter
  private String name639_2;
  @Getter
  private String name639_1;
  @Getter
  private String displayName;

  ISO639(String _2, String _1, String displayName) {
    this.name639_2 = _2;
    this.name639_1 = _1;
    this.displayName = displayName;
  }

  public static ISO639 fromISO639_2(String _2) {
    for (ISO639 iso: values()) {
      if (iso.name639_2.equalsIgnoreCase(_2))  {
        return iso;
      }
    }
    return UNKNWON;
  }

}
